version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: cimg/node
    steps:
      - checkout
      - run:
          name: Install dpkg and fakeroot other linux dependencies
          command: |
            sudo apt-get update -y
            sudo apt-get install -y dpkg fakeroot yarn rpm-build
            sudo apt-get install -y build-essential clang libdbus-1-dev libgtk-3-dev libnotify-dev libasound2-dev libcap-dev libcups2-dev libxtst-dev libxss1 libnss3-dev gcc-multilib g++-multilib curl gperf bison python3-dbusmock openjdk-8-jre
      - run:
          name: Update NPM
          command: "sudo npm install --global yarn"
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install Dependencies
          command: yarn
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Generate Builds
          command: yarn make
      - store_artifacts:
          path: ~/repo/build/

